name: build & deploy
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push to notifications
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notifications:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # environment:
    #   name: production
    steps:
      - uses: actions/checkout@master
      - name: Update notifications image
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.5
          command: set image --record deployment/notifications notifications=${{ secrets.DOCKERHUB_USERNAME }}/notifications:${{ github.sha }}
      - name: Verify notifications deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.5
          command: rollout status deployment/notifications
